name: Publish Release

on:
  push:
    branches: ["main"]
    paths-ignore:
      - .github/workflows/*
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Get Version From plugin.json
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "Flow.Launcher.Plugin.RepositoryQuickLauncher/plugin.json"
          prop_path: "Version"

      - name: Display version
        run: echo ${{steps.version.outputs.prop}}

      - name: Create Release Artifacts
        run: |
          dotnet publish Flow.Launcher.Plugin.RepositoryQuickLauncher -r win-x64  -c Release -o "Flow.Plugin.RepositoryQuickLauncher-${{steps.version.outputs.prop}}"
          7z a -tzip "Flow.Plugin.RepositoryQuickLauncher-${{steps.version.outputs.prop}}.zip" "./Flow.Plugin.RepositoryQuickLauncher-${{steps.version.outputs.prop}}/*"
          rm -r "Flow.Plugin.RepositoryQuickLauncher-${{steps.version.outputs.prop}}"

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: "Flow.Plugin.RepositoryQuickLauncher*.zip"
          tag_name: "v${{steps.version.outputs.prop}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
